# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comentario.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63omentario.proto\x12\x05model\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x0creceta.proto\"4\n\x0b\x43omentarios\x12%\n\ncomentario\x18\x01 \x03(\x0b\x32\x11.model.Comentario\"\x7f\n\nComentario\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x17\n\x0frecetaComentada\x18\x02 \x01(\t\x12\x19\n\x11usuarioComentario\x18\x03 \x01(\t\x12\x12\n\ncomentario\x18\x04 \x01(\t\x12\x1d\n\x06receta\x18\x05 \x01(\x0b\x32\r.model.Receta2\x8d\x01\n\x12\x43omentariosService\x12:\n\x0f\x66indAllByReceta\x12\x11.model.Comentario\x1a\x12.model.Comentarios\"\x00\x12;\n\x11GuardarComentario\x12\x11.model.Comentario\x1a\x11.model.Comentario\"\x00\x42\'\n\x14\x63om.chefencasa.modelB\x0f\x43omentarioProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'comentario_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024com.chefencasa.modelB\017ComentarioProto'
  _globals['_COMENTARIOS']._serialized_start=102
  _globals['_COMENTARIOS']._serialized_end=154
  _globals['_COMENTARIO']._serialized_start=156
  _globals['_COMENTARIO']._serialized_end=283
  _globals['_COMENTARIOSSERVICE']._serialized_start=286
  _globals['_COMENTARIOSSERVICE']._serialized_end=427
# @@protoc_insertion_point(module_scope)
