# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import denuncia_pb2 as denuncia__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class DenunciasServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FindAll = channel.unary_unary(
                '/model.DenunciasService/FindAll',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=denuncia__pb2.Denuncias.FromString,
                )


class DenunciasServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FindAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DenunciasServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FindAll': grpc.unary_unary_rpc_method_handler(
                    servicer.FindAll,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=denuncia__pb2.Denuncias.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'model.DenunciasService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DenunciasService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FindAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model.DenunciasService/FindAll',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            denuncia__pb2.Denuncias.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
