# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import user_pb2 as user__pb2
from . import receta_pb2 as receta__pb2
from . import favorito_pb2 as favorito__pb2


class FavoritosServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddFavorito = channel.unary_unary(
                '/model.FavoritosService/AddFavorito',
                request_serializer=favorito__pb2.Favorito.SerializeToString,
                response_deserializer=favorito__pb2.Favorito.FromString,
                )
        self.DeleteFavorito = channel.unary_unary(
                '/model.FavoritosService/DeleteFavorito',
                request_serializer=favorito__pb2.Favorito.SerializeToString,
                response_deserializer=favorito__pb2.Favorito.FromString,
                )
        self.FindAllById = channel.unary_unary(
                '/model.FavoritosService/FindAllById',
                request_serializer=favorito__pb2.Favorito.SerializeToString,
                response_deserializer=favorito__pb2.Favoritos.FromString,
                )


class FavoritosServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddFavorito(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFavorito(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindAllById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FavoritosServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddFavorito': grpc.unary_unary_rpc_method_handler(
                    servicer.AddFavorito,
                    request_deserializer=favorito__pb2.Favorito.FromString,
                    response_serializer=favorito__pb2.Favorito.SerializeToString,
            ),
            'DeleteFavorito': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFavorito,
                    request_deserializer=favorito__pb2.Favorito.FromString,
                    response_serializer=favorito__pb2.Favorito.SerializeToString,
            ),
            'FindAllById': grpc.unary_unary_rpc_method_handler(
                    servicer.FindAllById,
                    request_deserializer=favorito__pb2.Favorito.FromString,
                    response_serializer=favorito__pb2.Favoritos.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'model.FavoritosService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FavoritosService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddFavorito(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model.FavoritosService/AddFavorito',
            favorito__pb2.Favorito.SerializeToString,
            favorito__pb2.Favorito.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteFavorito(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model.FavoritosService/DeleteFavorito',
            favorito__pb2.Favorito.SerializeToString,
            favorito__pb2.Favorito.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FindAllById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model.FavoritosService/FindAllById',
            favorito__pb2.Favorito.SerializeToString,
            favorito__pb2.Favoritos.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
