# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: motivo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmotivo.proto\x12\x05model\x1a\x1bgoogle/protobuf/empty.proto\"(\n\x07Motivos\x12\x1d\n\x06motivo\x18\x01 \x03(\x0b\x32\r.model.Motivo\"$\n\x06Motivo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06motivo\x18\x02 \x01(\t2E\n\x0eMotivosService\x12\x33\n\x07\x46indAll\x12\x16.google.protobuf.Empty\x1a\x0e.model.Motivos\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'motivo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MOTIVOS']._serialized_start=52
  _globals['_MOTIVOS']._serialized_end=92
  _globals['_MOTIVO']._serialized_start=94
  _globals['_MOTIVO']._serialized_end=130
  _globals['_MOTIVOSSERVICE']._serialized_start=132
  _globals['_MOTIVOSSERVICE']._serialized_end=201
# @@protoc_insertion_point(module_scope)
