# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import popularidadUser_pb2 as popularidadUser__pb2
from . import user_pb2 as user__pb2


class PopularidadUsersServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FindAll = channel.unary_unary(
                '/model.PopularidadUsersService/FindAll',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=popularidadUser__pb2.PopularidadUsers.FromString,
                )
        self.GuardarPopularidadUser = channel.unary_unary(
                '/model.PopularidadUsersService/GuardarPopularidadUser',
                request_serializer=popularidadUser__pb2.PopularidadUser.SerializeToString,
                response_deserializer=popularidadUser__pb2.PopularidadUser.FromString,
                )


class PopularidadUsersServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FindAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GuardarPopularidadUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PopularidadUsersServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FindAll': grpc.unary_unary_rpc_method_handler(
                    servicer.FindAll,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=popularidadUser__pb2.PopularidadUsers.SerializeToString,
            ),
            'GuardarPopularidadUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GuardarPopularidadUser,
                    request_deserializer=popularidadUser__pb2.PopularidadUser.FromString,
                    response_serializer=popularidadUser__pb2.PopularidadUser.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'model.PopularidadUsersService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PopularidadUsersService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FindAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model.PopularidadUsersService/FindAll',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            popularidadUser__pb2.PopularidadUsers.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GuardarPopularidadUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model.PopularidadUsersService/GuardarPopularidadUser',
            popularidadUser__pb2.PopularidadUser.SerializeToString,
            popularidadUser__pb2.PopularidadUser.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
