# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import receta_pb2 as receta__pb2


class RecetasServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddReceta = channel.unary_unary(
                '/model.RecetasService/AddReceta',
                request_serializer=receta__pb2.Receta.SerializeToString,
                response_deserializer=receta__pb2.Receta.FromString,
                )
        self.FindAll = channel.unary_unary(
                '/model.RecetasService/FindAll',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=receta__pb2.Recetas.FromString,
                )
        self.ModificarReceta = channel.unary_unary(
                '/model.RecetasService/ModificarReceta',
                request_serializer=receta__pb2.Receta.SerializeToString,
                response_deserializer=receta__pb2.Receta.FromString,
                )
        self.FindById = channel.unary_unary(
                '/model.RecetasService/FindById',
                request_serializer=receta__pb2.Receta.SerializeToString,
                response_deserializer=receta__pb2.Receta.FromString,
                )
        self.FindFavoritos = channel.unary_unary(
                '/model.RecetasService/FindFavoritos',
                request_serializer=receta__pb2.Receta.SerializeToString,
                response_deserializer=receta__pb2.Recetas.FromString,
                )
        self.FindAllById = channel.unary_unary(
                '/model.RecetasService/FindAllById',
                request_serializer=receta__pb2.Receta.SerializeToString,
                response_deserializer=receta__pb2.Recetas.FromString,
                )
        self.FindAllBySeguidos = channel.unary_unary(
                '/model.RecetasService/FindAllBySeguidos',
                request_serializer=receta__pb2.Receta.SerializeToString,
                response_deserializer=receta__pb2.Recetas.FromString,
                )


class RecetasServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddReceta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModificarReceta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindFavoritos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindAllById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindAllBySeguidos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecetasServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddReceta': grpc.unary_unary_rpc_method_handler(
                    servicer.AddReceta,
                    request_deserializer=receta__pb2.Receta.FromString,
                    response_serializer=receta__pb2.Receta.SerializeToString,
            ),
            'FindAll': grpc.unary_unary_rpc_method_handler(
                    servicer.FindAll,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=receta__pb2.Recetas.SerializeToString,
            ),
            'ModificarReceta': grpc.unary_unary_rpc_method_handler(
                    servicer.ModificarReceta,
                    request_deserializer=receta__pb2.Receta.FromString,
                    response_serializer=receta__pb2.Receta.SerializeToString,
            ),
            'FindById': grpc.unary_unary_rpc_method_handler(
                    servicer.FindById,
                    request_deserializer=receta__pb2.Receta.FromString,
                    response_serializer=receta__pb2.Receta.SerializeToString,
            ),
            'FindFavoritos': grpc.unary_unary_rpc_method_handler(
                    servicer.FindFavoritos,
                    request_deserializer=receta__pb2.Receta.FromString,
                    response_serializer=receta__pb2.Recetas.SerializeToString,
            ),
            'FindAllById': grpc.unary_unary_rpc_method_handler(
                    servicer.FindAllById,
                    request_deserializer=receta__pb2.Receta.FromString,
                    response_serializer=receta__pb2.Recetas.SerializeToString,
            ),
            'FindAllBySeguidos': grpc.unary_unary_rpc_method_handler(
                    servicer.FindAllBySeguidos,
                    request_deserializer=receta__pb2.Receta.FromString,
                    response_serializer=receta__pb2.Recetas.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'model.RecetasService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RecetasService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddReceta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model.RecetasService/AddReceta',
            receta__pb2.Receta.SerializeToString,
            receta__pb2.Receta.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FindAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model.RecetasService/FindAll',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            receta__pb2.Recetas.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ModificarReceta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model.RecetasService/ModificarReceta',
            receta__pb2.Receta.SerializeToString,
            receta__pb2.Receta.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FindById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model.RecetasService/FindById',
            receta__pb2.Receta.SerializeToString,
            receta__pb2.Receta.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FindFavoritos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model.RecetasService/FindFavoritos',
            receta__pb2.Receta.SerializeToString,
            receta__pb2.Recetas.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FindAllById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model.RecetasService/FindAllById',
            receta__pb2.Receta.SerializeToString,
            receta__pb2.Recetas.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FindAllBySeguidos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model.RecetasService/FindAllBySeguidos',
            receta__pb2.Receta.SerializeToString,
            receta__pb2.Recetas.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
