# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import user_pb2 as user__pb2
from . import seguido_pb2 as seguido__pb2


class SeguidosServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddSeguido = channel.unary_unary(
                '/model.SeguidosService/AddSeguido',
                request_serializer=seguido__pb2.Seguido.SerializeToString,
                response_deserializer=seguido__pb2.Seguido.FromString,
                )
        self.DeleteSeguido = channel.unary_unary(
                '/model.SeguidosService/DeleteSeguido',
                request_serializer=seguido__pb2.Seguido.SerializeToString,
                response_deserializer=seguido__pb2.Seguido.FromString,
                )
        self.FindAllById = channel.unary_unary(
                '/model.SeguidosService/FindAllById',
                request_serializer=seguido__pb2.Seguido.SerializeToString,
                response_deserializer=seguido__pb2.Seguidos.FromString,
                )


class SeguidosServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddSeguido(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSeguido(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindAllById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SeguidosServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddSeguido': grpc.unary_unary_rpc_method_handler(
                    servicer.AddSeguido,
                    request_deserializer=seguido__pb2.Seguido.FromString,
                    response_serializer=seguido__pb2.Seguido.SerializeToString,
            ),
            'DeleteSeguido': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSeguido,
                    request_deserializer=seguido__pb2.Seguido.FromString,
                    response_serializer=seguido__pb2.Seguido.SerializeToString,
            ),
            'FindAllById': grpc.unary_unary_rpc_method_handler(
                    servicer.FindAllById,
                    request_deserializer=seguido__pb2.Seguido.FromString,
                    response_serializer=seguido__pb2.Seguidos.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'model.SeguidosService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SeguidosService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddSeguido(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model.SeguidosService/AddSeguido',
            seguido__pb2.Seguido.SerializeToString,
            seguido__pb2.Seguido.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteSeguido(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model.SeguidosService/DeleteSeguido',
            seguido__pb2.Seguido.SerializeToString,
            seguido__pb2.Seguido.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FindAllById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model.SeguidosService/FindAllById',
            seguido__pb2.Seguido.SerializeToString,
            seguido__pb2.Seguidos.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
