# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import user_pb2 as user__pb2

from . import seguido_pb2 as seguido__pb2



class SeguidosServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddSeguidos = channel.unary_unary(
                '/model.SeguidosService/AddSeguidos',
                request_serializer=seguido__pb2.Seguido.SerializeToString,
                response_deserializer=seguido__pb2.Seguido.FromString,
                )
        self.DeleteSeguidos = channel.unary_unary(
                '/model.SeguidosService/DeleteSeguidos',
                request_serializer=seguido__pb2.Seguido.SerializeToString,
                response_deserializer=seguido__pb2.Seguido.FromString,
                )
        self.DeleteSeguidores = channel.unary_unary(
                '/model.SeguidosService/DeleteSeguidores',
                request_serializer=seguido__pb2.Seguido.SerializeToString,
                response_deserializer=seguido__pb2.Seguido.FromString,
                )
        self.CheckSeguidos = channel.unary_unary(
                '/model.SeguidosService/CheckSeguidos',
                request_serializer=seguido__pb2.Seguido.SerializeToString,
                response_deserializer=seguido__pb2.FlagSeguido.FromString,
                )


class SeguidosServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddSeguidos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSeguidos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSeguidores(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckSeguidos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SeguidosServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddSeguidos': grpc.unary_unary_rpc_method_handler(
                    servicer.AddSeguidos,
                    request_deserializer=seguido__pb2.Seguido.FromString,
                    response_serializer=seguido__pb2.Seguido.SerializeToString,
            ),
            'DeleteSeguidos': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSeguidos,
                    request_deserializer=seguido__pb2.Seguido.FromString,
                    response_serializer=seguido__pb2.Seguido.SerializeToString,
            ),
            'DeleteSeguidores': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSeguidores,
                    request_deserializer=seguido__pb2.Seguido.FromString,
                    response_serializer=seguido__pb2.Seguido.SerializeToString,
            ),
            'CheckSeguidos': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckSeguidos,
                    request_deserializer=seguido__pb2.Seguido.FromString,
                    response_serializer=seguido__pb2.FlagSeguido.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'model.SeguidosService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SeguidosService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddSeguidos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model.SeguidosService/AddSeguidos',
            seguido__pb2.Seguido.SerializeToString,
            seguido__pb2.Seguido.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteSeguidos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model.SeguidosService/DeleteSeguidos',
            seguido__pb2.Seguido.SerializeToString,
            seguido__pb2.Seguido.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteSeguidores(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model.SeguidosService/DeleteSeguidores',
            seguido__pb2.Seguido.SerializeToString,
            seguido__pb2.Seguido.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckSeguidos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model.SeguidosService/CheckSeguidos',
            seguido__pb2.Seguido.SerializeToString,
            seguido__pb2.FlagSeguido.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
