spring.application.name: chefencasa
spring.output.ansi.enabled: always

management.endpoints.web.exposure.include: metrics
management.endpoint.metrics.enabled: true


# spring.datasource.url
spring.datasource.url: jdbc:mysql://${SPRING_DATASOURCE_DB:localhost}:3306/chefencasa

# spring.datasource.username
spring.datasource.username : ${SPRING_DATASOURCE_USERNAME:root}

# spring.datasource.password
spring.datasource.password : ${SPRING_DATASOURCE_PASSWORD:root}


# spring.jpa.show-sql
spring.jpa.show-sql : true

# spring.jpa.hibernate.ddl-auto
spring.jpa.hibernate.ddl-auto : update

# spring.jpa.properties.dialect
spring.jpa.properties.dialect : org.hibernate.dialect.MySQL8Dialect

server.port: ${SPRING_PORT:8080}
# Configuración de Kafka
spring:
  kafka:
    bootstrap-servers: ${KAFKA-SERVER:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer