# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\raccount.proto\x12\x05model\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\"+\n\x08\x41\x63\x63ounts\x12\x1f\n\x07\x61\x63\x63ount\x18\x01 \x03(\x0b\x32\x0e.model.Account\":\n\x07\x41\x63\x63ount\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06number\x18\x02 \x01(\t\x12\x13\n\x0b\x63ustomer_id\x18\x03 \x01(\x05\x32\xec\x01\n\x0f\x41\x63\x63ountsService\x12>\n\x0c\x46indByNumber\x12\x1c.google.protobuf.StringValue\x1a\x0e.model.Account\"\x00\x12\x33\n\x0e\x46indByCustomer\x12\x0e.model.Account\x1a\x0f.model.Accounts\"\x00\x12\x34\n\x07\x46indAll\x12\x16.google.protobuf.Empty\x1a\x0f.model.Accounts\"\x00\x12.\n\nAddAccount\x12\x0e.model.Account\x1a\x0e.model.Account\"\x00\x42$\n\x14\x63om.chefencasa.modelB\x0c\x41\x63\x63ountProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'account_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024com.chefencasa.modelB\014AccountProto'
  _globals['_ACCOUNTS']._serialized_start=85
  _globals['_ACCOUNTS']._serialized_end=128
  _globals['_ACCOUNT']._serialized_start=130
  _globals['_ACCOUNT']._serialized_end=188
  _globals['_ACCOUNTSSERVICE']._serialized_start=191
  _globals['_ACCOUNTSSERVICE']._serialized_end=427
# @@protoc_insertion_point(module_scope)
