# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import rol_pb2 as rol__pb2


class RolsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddRol = channel.unary_unary(
                '/model.RolsService/AddRol',
                request_serializer=rol__pb2.Rol.SerializeToString,
                response_deserializer=rol__pb2.Rol.FromString,
                )


class RolsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddRol(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RolsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddRol': grpc.unary_unary_rpc_method_handler(
                    servicer.AddRol,
                    request_deserializer=rol__pb2.Rol.FromString,
                    response_serializer=rol__pb2.Rol.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'model.RolsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RolsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddRol(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model.RolsService/AddRol',
            rol__pb2.Rol.SerializeToString,
            rol__pb2.Rol.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
