# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rol.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trol.proto\x12\x05model\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x1f\n\x04Rols\x12\x17\n\x03rol\x18\x01 \x03(\x0b\x32\n.model.Rol\"!\n\x03Rol\x12\r\n\x05idRol\x18\x01 \x01(\x05\x12\x0b\n\x03rol\x18\x02 \x01(\t21\n\x0bRolsService\x12\"\n\x06\x41\x64\x64Rol\x12\n.model.Rol\x1a\n.model.Rol\"\x00\x42 \n\x14\x63om.chefencasa.modelB\x08RolProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rol_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024com.chefencasa.modelB\010RolProto'
  _globals['_ROLS']._serialized_start=81
  _globals['_ROLS']._serialized_end=112
  _globals['_ROL']._serialized_start=114
  _globals['_ROL']._serialized_end=147
  _globals['_ROLSSERVICE']._serialized_start=149
  _globals['_ROLSSERVICE']._serialized_end=198
# @@protoc_insertion_point(module_scope)
