# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x05model\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\"\n\x05Users\x12\x19\n\x04user\x18\x01 \x03(\x0b\x32\x0b.model.User\"_\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x10\n\x08\x61pellido\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\r\n\x05\x63lave\x18\x05 \x01(\t\x12\x0b\n\x03rol\x18\x06 \x01(\t2h\n\x0cUsersService\x12%\n\x07\x41\x64\x64User\x12\x0b.model.User\x1a\x0b.model.User\"\x00\x12\x31\n\x13ValidarCredenciales\x12\x0b.model.User\x1a\x0b.model.User\"\x00\x42!\n\x14\x63om.chefencasa.modelB\tUserProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024com.chefencasa.modelB\tUserProto'
  _globals['_USERS']._serialized_start=82
  _globals['_USERS']._serialized_end=116
  _globals['_USER']._serialized_start=118
  _globals['_USER']._serialized_end=213
  _globals['_USERSSERVICE']._serialized_start=215
  _globals['_USERSSERVICE']._serialized_end=319
# @@protoc_insertion_point(module_scope)
